#!/usr/bin/env ruby
# Copyright 2015 Wojciech A. Koszek <wojciech@koszek.com>
#
# Inspired by:
#
# https://gist.github.com/davidblewett/53047c4c7757b663c11b
# http://pentestmonkey.net/blog/ssh-with-no-tty
#
# 1st didn't work for me out of the box on MacOSX. I made this script instead to
# handle both adding all keys and passing the passphrase to an ssh-add.

G_KEYS_PATH = "/w/c/dot.ssh/"
fn_abs = File.absolute_path($0)

if not `lpass --version` =~ /LastPass/ then
	print "You don't have LastPass CLI installed. Do:\n"
	print "brew install lpass    # on Mac\n"
	print "apt-get install lpass # on Ubuntu\n"
	exit 64
end

if ENV["KEY_ID"] then
	r = `lpass show --field Passphrase #{ENV['KEY_ID']}`
	print r
else
	# Lines will be e.g.: 'Secure Notes\SSH/bitbucket [id: 5505843262]'
	raw_lines = `lpass ls "Secure Notes\\SSH"`
	lines = raw_lines.split("\n").select { |l| l if l =~ /^Secure/ }

	# Use key's name, make path out of it, attempt to add it by its ID
	lines.each.map{ |l| l.scan(/\w+/)}.each do |sec, notes, ssh, key_name, id_str, key_id|
		fork do
			ENV["KEY_ID"] = key_id
			ENV["SSH_ASKPASS"] = fn_abs
			ENV["DISPLAY"] = "foo"
			exec "ssh-add #{G_KEYS_PATH}/#{key_name} < /dev/null"
		end
		Process.wait
	end
end
