#!/usr/bin/env ruby
# Copyright 2015 Wojciech A. Koszek <wojciech@koszek.com>
#
# Inspired by:
#
# https://gist.github.com/davidblewett/53047c4c7757b663c11b
# http://pentestmonkey.net/blog/ssh-with-no-tty
#
# 1st didn't work for me out of the box on MacOSX. I made this script instead to
# handle both adding all keys and passing the passphrase to an ssh-add.

fn_abs = File.absolute_path($0)

if not `lpass --version` =~ /LastPass/ then
	print "You don't have LastPass CLI installed. Do:\n"
	print "brew install lpass    # on Mac\n"
	print "apt-get install lpass # on Ubuntu\n"
	exit 64
end

g_keys_path = ENV["HOME"] + "/.ssh"
ARGV.each do |arg|
	if arg =~ /--help/ then
		print "lastpass-ssh:\n"
		print "  --key-from-lastpass    get SSH \n"
		print "  --help                 print this help\n"
		exit 0
	elsif arg =~ /--keys-path/ then
		ARGV.shift
		g_keys_path = ARGV.pop()
	end
	ARGV.shift
end
if not g_keys_path then
	print "you must pass path to --keys-path\n"
	exit 64
end

if ENV["KEY_ID"] then
	r = `lpass show --field Passphrase #{ENV['KEY_ID']}`
	print r
else
	# Lines will be e.g.: 'Secure Notes\SSH/bitbucket [id: 5505843262]'
	raw_lines = `lpass ls "Secure Notes\\SSH"`
	lines = raw_lines.split("\n").select { |l| l if l =~ /^Secure/ }

	# Use key's name, make path out of it, attempt to add it by its ID
	lines.each.map{ |l| l.scan(/\w+/)}.each do |sec, notes, ssh, key_name, id_str, key_id|
		fork do
			ENV["KEY_ID"] = key_id
			ENV["SSH_ASKPASS"] = fn_abs
			ENV["DISPLAY"] = "foo"
			print "LastPass key ID #{key_id} "
			if key_name =~ /^lpass_/ then
				print "before\n"
				key_body = `lpass show --notes #{key_id}`
				print "after\n"
				if key_body.strip().empty? then
					print "LastPass 'Notes' section of key " +
						"'#{key_name}' is empty (no key defined)!\n"
					exit 1
				end
				print "execing\n"
				exec "lpass show --notes #{key_id} | ssh-add - < /dev/null"
			else
				exec "ssh-add #{g_keys_path}/#{key_name} < /dev/null"
			end

		end
		Process.wait
	end
end
